version: '3.8'

services:
  # Фронтенд приложение
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8080/api
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

  # Бэкенд API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/360app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=86400000
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  # База данных
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=360app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: